In [1]:
import os
import json

import numpy as np
import pandas as pd

In [2]:
runs = [
    os.path.join('experiments', str(x)) for x in range(1905, 1940)
]

assert len(runs) == 35, len(runs)

In [3]:
soln_number_to_name = {
    1: 'Plane waves',
    2: 'Radial waves',
    3: 'Hopf fibration',
    4: 'Random solution'
}

In [4]:
df = pd.DataFrame(
    columns=list(json.load(open(os.path.join(runs[0], 'hparams.json'))).keys())
    + [
        'soln_name',
        'min_mse_val',
        'time_to_min_mse_val',
        'min_rel_l2_error',
        'time_to_min_rel_l2_error',
        'exp_num',
        # 'time_to_5p_rel_l2_error'
    ]
)

for run in runs:
    info = json.load(open(os.path.join(run, 'hparams.json')))
    
    info['exp_num'] = int(run.split('/')[1])

    assert (info['do_masking'] and info['add_bc']) or (not info['add_bc'])
    
    info['soln_name'] = soln_number_to_name[info['soln']]
    
    log = pd.read_csv(os.path.join(run, 'log.tsv'), sep='\t')
    
    # print(log['training_time'].cumsum().max())
    
    if os.path.exists(os.path.join(run, 'init_time.txt')):
        init_time = float(open(os.path.join(run, 'init_time.txt')).read())
    else:
        init_time = 0.
    
    # epoch where we reach minimum validation MSE
    min_mse_val = log['mse_val'].min()
    info['min_mse_val'] = min_mse_val
    
    min_mse_val_epoch = int(log[log['mse_val'] == min_mse_val].iloc[0]['epoch'])
    # how much training time to get there?
    info['time_to_min_mse_val'] = log[log['epoch'] <= min_mse_val_epoch]['training_time'].sum().item() + init_time
    
    # epoch where we reach minimum validation relative L2 error
    min_rel_l2_error = log['rel_l2_error'].min()
    info['min_rel_l2_error'] = min_rel_l2_error
    
    min_rel_l2_error_epoch = int(log[log['rel_l2_error'] <= min_rel_l2_error].iloc[0]['epoch'])
    info['time_to_min_rel_l2_error'] = log[log['epoch'] <= min_rel_l2_error_epoch]['training_time'].sum().item() + init_time
    
    # epoch where we first reach 5% relative error
    # first_5p_epoch = int(log[log['rel_l2_error'] < 0.05].iloc[0]['epoch'])
    # info['time_to_5p_rel_l2_error'] = log[log['epoch'] <= first_5p_epoch]['training_time'].sum().item() + init_time
    
    df.loc[len(df)] = info

In [5]:
df

,num_ps,input_dim,output_dim,max_epochs,max_time,log_freq,verbose,restart_patience,restart_tolerance,restarts,...,mu_inputs,sigma_inputs,mu_targets,sigma_targets,soln_name,min_mse_val,time_to_min_mse_val,min_rel_l2_error,time_to_min_rel_l2_error,exp_num
0,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.42362719774246216, 0.4947110712528229, 0.45...","[0.3202417194843292, 0.35279783606529236, 0.37...","[-0.03345438838005066, 0.030121732503175735, 0...","[0.11443682014942169, 0.13271602988243103, 0.1...",Random solution,0.004024,4.870581,0.443758,4.870581,1905
1,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.42362719774246216, 0.4947110712528229, 0.45...","[0.3202417194843292, 0.35279783606529236, 0.37...","[-0.03345438838005066, 0.030121732503175735, 0...","[0.11443682014942169, 0.13271602988243103, 0.1...",Random solution,0.005183,23.311585,0.503609,23.311585,1906
2,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.42362719774246216, 0.4947110712528229, 0.45...","[0.3202417194843292, 0.35279783606529236, 0.37...","[-0.03345438838005066, 0.030121732503175735, 0...","[0.11443682014942169, 0.13271602988243103, 0.1...",Random solution,0.005928,160.262363,0.538580,160.262363,1907
3,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.42362719774246216, 0.4947110712528229, 0.45...","[0.3202417194843292, 0.35279783606529236, 0.37...","[-0.03345438838005066, 0.030121732503175735, 0...","[0.11443682014942169, 0.13271602988243103, 0.1...",Random solution,0.005251,383.937545,0.506907,383.937545,1908
4,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.42362719774246216, 0.4947110712528229, 0.45...","[0.3202417194843292, 0.35279783606529236, 0.37...","[-0.03345438838005066, 0.030121732503175735, 0...","[0.11443682014942169, 0.13271602988243103, 0.1...",Random solution,0.009057,3.340224,0.665738,3.340224,1909
5,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.42362719774246216, 0.4947110712528229, 0.45...","[0.3202417194843292, 0.35279783606529236, 0.37...","[-0.03345438838005066, 0.030121732503175735, 0...","[0.11443682014942169, 0.13271602988243103, 0.1...",Random solution,0.014166,5.176386,0.832589,5.176386,1910
6,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.42362719774246216, 0.4947110712528229, 0.45...","[0.3202417194843292, 0.35279783606529236, 0.37...","[-0.03345438838005066, 0.030121732503175735, 0...","[0.11443682014942169, 0.13271602988243103, 0.1...",Random solution,0.017220,13.073284,0.917942,13.073284,1911
7,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.41867607831954956, 0.5020413398742676, 0.49...","[0.3178815543651581, 0.35919785499572754, 0.35...","[-0.043669361621141434, 0.04419444501399994, 0...","[0.1148931235074997, 0.14607803523540497, 0.16...",Random solution,0.000050,100.900954,0.049886,100.900954,1912
8,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.41867607831954956, 0.5020413398742676, 0.49...","[0.3178815543651581, 0.35919785499572754, 0.35...","[-0.043669361621141434, 0.04419444501399994, 0...","[0.1148931235074997, 0.14607803523540497, 0.16...",Random solution,0.000050,126.941000,0.049999,126.941000,1913
9,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.41867607831954956, 0.5020413398742676, 0.49...","[0.3178815543651581, 0.35919785499572754, 0.35...","[-0.043669361621141434, 0.04419444501399994, 0...","[0.1148931235074997, 0.14607803523540497, 0.16...",Random solution,0.000050,92.240875,0.049953,92.240875,1914
10,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.41867607831954956, 0.5020413398742676, 0.49...","[0.3178815543651581, 0.35919785499572754, 0.35...","[-0.043669361621141434, 0.04419444501399994, 0...","[0.1148931235074997, 0.14607803523540497, 0.16...",Random solution,0.000050,99.746262,0.049983,99.746262,1915
11,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.41867607831954956, 0.5020413398742676, 0.49...","[0.3178815543651581, 0.35919785499572754, 0.35...","[-0.043669361621141434, 0.04419444501399994, 0...","[0.1148931235074997, 0.14607803523540497, 0.16...",Random solution,0.000051,594.190475,0.050106,594.190475,1916
12,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.41867607831954956, 0.5020413398742676, 0.49...","[0.3178815543651581, 0.35919785499572754, 0.35...","[-0.043669361621141434, 0.04419444501399994, 0...","[0.1148931235074997, 0.14607803523540497, 0.16...",Random solution,0.000697,598.089614,0.186056,598.089614,1917
13,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.41867607831954956, 0.5020413398742676, 0.49...","[0.3178815543651581, 0.35919785499572754, 0.35...","[-0.043669361621141434, 0.04419444501399994, 0...","[0.1148931235074997, 0.14607803523540497, 0.16...",Random solution,0.004825,577.271808,0.489381,577.271808,1918
14,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.4305742681026459, 0.495451956987381, 0.5005...","[0.3198383152484894, 0.3629661202430725, 0.361...","[-0.04303685575723648, 0.04444243013858795, 0....","[0.11678407341241837, 0.14423368871212006, 0.1...",Random solution,0.000050,93.335602,0.049878,93.335602,1919
15,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.4305742681026459, 0.495451956987381, 0.5005...","[0.3198383152484894, 0.3629661202430725, 0.361...","[-0.04303685575723648, 0.04444243013858795, 0....","[0.11678407341241837, 0.14423368871212006, 0.1...",Random solution,0.000050,91.222001,0.049795,91.222001,1920
16,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.4305742681026459, 0.495451956987381, 0.5005...","[0.3198383152484894, 0.3629661202430725, 0.361...","[-0.04303685575723648, 0.04444243013858795, 0....","[0.11678407341241837, 0.14423368871212006, 0.1...",Random solution,0.000046,68.902766,0.048144,68.902766,1921
17,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.4305742681026459, 0.495451956987381, 0.5005...","[0.3198383152484894, 0.3629661202430725, 0.361...","[-0.04303685575723648, 0.04444243013858795, 0....","[0.11678407341241837, 0.14423368871212006, 0.1...",Random solution,0.000027,69.662559,0.036566,69.662559,1922
18,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.4305742681026459, 0.495451956987381, 0.5005...","[0.3198383152484894, 0.3629661202430725, 0.361...","[-0.04303685575723648, 0.04444243013858795, 0....","[0.11678407341241837, 0.14423368871212006, 0.1...",Random solution,0.000046,69.670535,0.048017,69.670535,1923
19,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.4305742681026459, 0.495451956987381, 0.5005...","[0.3198383152484894, 0.3629661202430725, 0.361...","[-0.04303685575723648, 0.04444243013858795, 0....","[0.11678407341241837, 0.14423368871212006, 0.1...",Random solution,0.000422,597.790859,0.145233,597.790859,1924
20,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.4305742681026459, 0.495451956987381, 0.5005...","[0.3198383152484894, 0.3629661202430725, 0.361...","[-0.04303685575723648, 0.04444243013858795, 0....","[0.11678407341241837, 0.14423368871212006, 0.1...",Random solution,0.006163,593.791376,0.555143,593.791376,1925
21,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.4296979606151581, 0.5000619888305664, 0.499...","[0.3199615776538849, 0.3617068827152252, 0.361...","[-0.04326110705733299, 0.04385317489504814, 0....","[0.1163853108882904, 0.1430508941411972, 0.160...",Random solution,0.000050,131.551613,0.049755,131.551613,1926
22,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.4296979606151581, 0.5000619888305664, 0.499...","[0.3199615776538849, 0.3617068827152252, 0.361...","[-0.04326110705733299, 0.04385317489504814, 0....","[0.1163853108882904, 0.1430508941411972, 0.160...",Random solution,0.000047,123.217603,0.048157,123.217603,1927
23,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.4296979606151581, 0.5000619888305664, 0.499...","[0.3199615776538849, 0.3617068827152252, 0.361...","[-0.04326110705733299, 0.04385317489504814, 0....","[0.1163853108882904, 0.1430508941411972, 0.160...",Random solution,0.000049,96.854208,0.049380,96.854208,1928
24,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.4296979606151581, 0.5000619888305664, 0.499...","[0.3199615776538849, 0.3617068827152252, 0.361...","[-0.04326110705733299, 0.04385317489504814, 0....","[0.1163853108882904, 0.1430508941411972, 0.160...",Random solution,0.000040,67.393358,0.044218,67.393358,1929
25,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.4296979606151581, 0.5000619888305664, 0.499...","[0.3199615776538849, 0.3617068827152252, 0.361...","[-0.04326110705733299, 0.04385317489504814, 0....","[0.1163853108882904, 0.1430508941411972, 0.160...",Random solution,0.000051,92.923485,0.049946,92.923485,1930
26,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.4296979606151581, 0.5000619888305664, 0.499...","[0.3199615776538849, 0.3617068827152252, 0.361...","[-0.04326110705733299, 0.04385317489504814, 0....","[0.1163853108882904, 0.1430508941411972, 0.160...",Random solution,0.000297,600.432278,0.121196,600.432278,1931
27,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.4296979606151581, 0.5000619888305664, 0.499...","[0.3199615776538849, 0.3617068827152252, 0.361...","[-0.04326110705733299, 0.04385317489504814, 0....","[0.1163853108882904, 0.1430508941411972, 0.160...",Random solution,0.003114,606.995913,0.392103,606.995913,1932
28,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.4280603528022766, 0.4999038875102997, 0.499...","[0.31925448775291443, 0.36182940006256104, 0.3...","[-0.0436134971678257, 0.04478602111339569, 0.0...","[0.11640086770057678, 0.14308258891105652, 0.1...",Random solution,0.000044,129.752493,0.046772,129.752493,1933
29,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.4280603528022766, 0.4999038875102997, 0.499...","[0.31925448775291443, 0.36182940006256104, 0.3...","[-0.0436134971678257, 0.04478602111339569, 0.0...","[0.11640086770057678, 0.14308258891105652, 0.1...",Random solution,0.000043,153.954113,0.046282,153.954113,1934
30,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.4280603528022766, 0.4999038875102997, 0.499...","[0.31925448775291443, 0.36182940006256104, 0.3...","[-0.0436134971678257, 0.04478602111339569, 0.0...","[0.11640086770057678, 0.14308258891105652, 0.1...",Random solution,0.000041,104.974861,0.045153,104.974861,1935
31,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.4280603528022766, 0.4999038875102997, 0.499...","[0.31925448775291443, 0.36182940006256104, 0.3...","[-0.0436134971678257, 0.04478602111339569, 0.0...","[0.11640086770057678, 0.14308258891105652, 0.1...",Random solution,0.000040,85.787659,0.044545,85.787659,1936
32,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.4280603528022766, 0.4999038875102997, 0.499...","[0.31925448775291443, 0.36182940006256104, 0.3...","[-0.0436134971678257, 0.04478602111339569, 0.0...","[0.11640086770057678, 0.14308258891105652, 0.1...",Random solution,0.000049,123.786158,0.049335,123.786158,1937
33,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.4280603528022766, 0.4999038875102997, 0.499...","[0.31925448775291443, 0.36182940006256104, 0.3...","[-0.0436134971678257, 0.04478602111339569, 0.0...","[0.11640086770057678, 0.14308258891105652, 0.1...",Random solution,0.000205,607.634357,0.101114,607.634357,1938
34,2,3,6,10000,10,100,False,10,0.1,False,...,"[0.4280603528022766, 0.4999038875102997, 0.499...","[0.31925448775291443, 0.36182940006256104, 0.3...","[-0.0436134971678257, 0.04478602111339569, 0.0...","[0.11640086770057678, 0.14308258891105652, 0.1...",Random solution,0.004262,662.287708,0.461303,662.287708,1939

In [6]:
df['min_rel_l2_error'] = df['min_rel_l2_error'] * 100

df = df.round(1)

for col in df.columns:
    df[col] = df[col].astype(str)

In [7]:
results = df[[
    # 'exp_num',
    # 'soln_name',
    'width',
    # 'activation',
    'n_train',
    # 'time_to_5p_rel_l2_error',
    'min_rel_l2_error',
    'time_to_min_rel_l2_error',
]].rename(columns={
    # 'exp_num': 'Experiment #',
    # 'time_to_5p_rel_l2_error': 'Time to <5% RL2E. (s)',
    'time_to_min_rel_l2_error': 'Time to min. RL2E. (s)',
    'min_rel_l2_error': 'Min. RL2E. (%)',
    # 'soln_name': 'Solution',
    'width': 'Network width',
    # 'activation': 'Activation',
    'n_train': '# points'
})

results

   Network width # points Min. RL2E. (%) Time to min. RL2E. (s)
0           2000      100           44.4                    4.9
1           4000      100           50.4                   23.3
2           8000      100           53.9                  160.3
3          16000      100           50.7                  383.9
4          32000      100           66.6                    3.3
5          64000      100           83.3                    5.2
6         128000      100           91.8                   13.1
7           2000     1000            5.0                  100.9
8           4000     1000            5.0                  126.9
9           8000     1000            5.0                   92.2
10         16000     1000            5.0                   99.7
11         32000     1000            5.0                  594.2
12         64000     1000           18.6                  598.1
13        128000     1000           48.9                  577.3
14          2000    10000            5.0                   93.3
15          4000    10000            5.0                   91.2
16          8000    10000            4.8                   68.9
17         16000    10000            3.7                   69.7
18         32000    10000            4.8                   69.7
19         64000    10000           14.5                  597.8
20        128000    10000           55.5                  593.8
21          2000   100000            5.0                  131.6
22          4000   100000            4.8                  123.2
23          8000   100000            4.9                   96.9
24         16000   100000            4.4                   67.4
25         32000   100000            5.0                   92.9
26         64000   100000           12.1                  600.4
27        128000   100000           39.2                  607.0
28          2000  1000000            4.7                  129.8
29          4000  1000000            4.6                  154.0
30          8000  1000000            4.5                  105.0
31         16000  1000000            4.5                   85.8
32         32000  1000000            4.9                  123.8
33         64000  1000000           10.1                  607.6
34        128000  1000000           46.1                  662.3

In [8]:
print(results.to_latex(index=False))

\begin{tabular}{llll}
\toprule
Network width & # points & Min. RL2E. (%) & Time to min. RL2E. (s) \\
\midrule
2000 & 100 & 44.4 & 4.9 \\
4000 & 100 & 50.4 & 23.3 \\
8000 & 100 & 53.9 & 160.3 \\
16000 & 100 & 50.7 & 383.9 \\
32000 & 100 & 66.6 & 3.3 \\
64000 & 100 & 83.3 & 5.2 \\
128000 & 100 & 91.8 & 13.1 \\
2000 & 1000 & 5.0 & 100.9 \\
4000 & 1000 & 5.0 & 126.9 \\
8000 & 1000 & 5.0 & 92.2 \\
16000 & 1000 & 5.0 & 99.7 \\
32000 & 1000 & 5.0 & 594.2 \\
64000 & 1000 & 18.6 & 598.1 \\
128000 & 1000 & 48.9 & 577.3 \\
2000 & 10000 & 5.0 & 93.3 \\
4000 & 10000 & 5.0 & 91.2 \\
8000 & 10000 & 4.8 & 68.9 \\
16000 & 10000 & 3.7 & 69.7 \\
32000 & 10000 & 4.8 & 69.7 \\
64000 & 10000 & 14.5 & 597.8 \\
128000 & 10000 & 55.5 & 593.8 \\
2000 & 100000 & 5.0 & 131.6 \\
4000 & 100000 & 4.8 & 123.2 \\
8000 & 100000 & 4.9 & 96.9 \\
16000 & 100000 & 4.4 & 67.4 \\
32000 & 100000 & 5.0 & 92.9 \\
64000 & 100000 & 12.1 & 600.4 \\
128000 & 100000 & 39.2 & 607.0 \\
2000 & 1000000 & 4.7 & 129.8 \\
4000 & 1000000 & 4.6 & 154.0 \\
8000 & 1000000 & 4.5 & 105.0 \\
16000 & 1000000 & 4.5 & 85.8 \\
32000 & 1000000 & 4.9 & 123.8 \\
64000 & 1000000 & 10.1 & 607.6 \\
128000 & 1000000 & 46.1 & 662.3 \\
\bottomrule
\end{tabular}